# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  # command = "cd themes/docsy && git submodule update -f --init && cd ../../.. && hugo"
  command = "ls -la && git submodule update -f --init && npm install -D --save postcss-cli && npm install -D --save postcss && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.78.2"
  HUGO_THEME = "docsy"
  HUGO_ENV = "production"
